{
  "models": {
    "mistral": "N",
    "fanar_rag": "N",
    "fanar_validated": "Y",
    fanar_validated_detailed: "N",
    "allam_7b": "N"
  },
  "paths": {
    "input_dir": "../data",
    "output_dir": "../results/prediction"
  }
}
